config/routes.rb
Rails.application.routes.draw do
  constraints ->  request { request.session[:user_id].present? } do
    root to: 'tasks#index'
  end
  root to: 'sessions#new'
  resources :tasks
  resources :users, only:[:new, :create, :show]
  resources :sessions, only:[:new, :create, :destroy]
  resources :labels

  namespace :admin do
    resources :users do
      collection do
        get :error
      end
    end
    resources :labels
  end
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  validates :name, presence: true, length: { in: 1..20 }
  scope :latest, -> { order(created_at: :asc) }
end

app/controllers/admin/labels_controller.rb
class Admin::LabelsController < ApplicationController
  before_action :require_admin
  before_action :set_admin_label, only: [:edit, :update, :destroy]

  def index
    @labels = Label.latest
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to admin_labels_path, notice: 'ラベルを作成しました'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @label.update(label_params)
      redirect_to admin_labels_path, notice: "ID#{@label.id}番のラベルを編集しました"
    else
      flash.now[:danger] = "ID#{@label.id}番のユーザーの編集に失敗しました"
      render 'edit'
    end
  end

  def destroy
    @label.destroy
    redirect_to admin_labels_path, notice: "ID#{@label.id}番のラベルを削除しました"
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end

  def set_admin_label
    @label = Label.find(params[:id])
  end

  def require_admin
    if logged_in?
      unless Admin.find_by(user_id: current_user.id)
        flash[:error] = 'このセクションにアクセス出来るのは、管理者権限のあるユーザーのみです'
        render :layout => 'admin/error', action: 'error'
      end
    else
      flash[:error] = 'ログインしていたアカウントが見つかりません'
      redirect_to root_path
    end
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :require_login, only: [:new, :create]
  before_action :set_user_label, only: [:edit, :update, :destroy]

  def index
    @user_labels = UserLabel.latest
  end

  def new
    @user_label = UserLabel.new
  end

  def create
    @user_label = UserLabel.new(user_label_params)
    if @user_label.save
      redirect_to labels_path, notice: 'ラベルを作成しました'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user_label.update(user_label_params)
      redirect_to labels_path, notice: "ID#{@user_label.id}番のラベルを編集しました"
    else
      flash.now[:danger] = "ID#{@user_label.id}番のユーザーの編集に失敗しました"
      render 'edit'
    end
  end

  def destroy
    @user_label.destroy
    redirect_to labels_path, notice: "ID#{@user_label.id}番のラベルを削除しました"
  end

  private

  def user_label_params
    params.require(:user_label).permit(:name, :user_id)
  end

  def set_user_label
    @user_label = UserLabel.find(params[:id])
  end

  def require_login
    unless logged_in?
      flash[:error] = 'このセクションにアクセスするにはログインして下さい'
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/labels_helper.rb
module Admin::LabelsHelper
end

app/views/labels/edit.html.erb
<div class='row field'>
  <div class='col-md-12'>
    <h2>ラベル編集画面</h2>
  </div>
</div>

<div class='row field'>
  <div class='col-md-12'>
    <% if @user_label.errors.any? %>
      <div id='error_explanation' class='alert alert alert-danger'>
        <h2>このラベルを保存出来ません【<%= pluralize(@user_label.errors.count, 'error') %>】</h2>
        <ul>
          <% @user_label.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<div class= 'row field'>
  <div class='col-md-12'>
    <%= form_with(model: @user_label, url: label_path(@user_label.id), method: :patch, local: true) do |label| %>
      <table>
        <tr><th><%= label.label :name %></th><td><%= label.text_field :name %></td></tr>
      </table>
      <%= label.submit 'ラベル更新する', class: 'btn btn-primary btn-sm' %>
      <%= link_to 'ラベル一覧', labels_path, class: 'btn btn-success btn-sm' %>
    <% end %>
  </div>
</div>

app/views/labels/index.html.erb
<div class='row field'>
  <div class='col-md-12'>
    <h2><%= current_user.name %>の作成したラベル一覧画面</h2>
  </div>
</div>

<div class='row field'>
  <div class='col-md-12 field'>
    <%= link_to 'ラベルを新規登録する', new_label_path, class: 'btn btn-success btn-sm' %>
    <%= link_to 'タスク一覧画面', tasks_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>

<div class='row field'>
  <div class='col-md-12'>
    <table border=1>
      <tr>
        <th>id</th>
        <td>name</td>
        <td>タスク数</td>
      </tr>

      <% @user_labels.where(user_id: current_user.id).each do |label| %>
        <tr>
          <th><%= label.id %></th>
          <td><%= label.name %></td>
          <td></td>
          <td><%= link_to '編集', edit_label_path(label.id), class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to '削除', label_path(label.id), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/labels/new.html.erb
<div class='row field'>
  <div class='col-md-12'>
    <h2>ラベル新規登録画面</h2>
  </div>
</div>

<div class='row field'>
  <div class='col-md-12'>
    <% if @user_label.errors.any? %>
      <div id='error_explanation' class='alert alert-danger'>
        <h2>このラベルは保存出来ません【<%= pluralize(@user_label.errors.count, 'error') %>】</h2>
        <ul>
          <% @user_label.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<div class= 'row field'>
  <div class='col-md-12'>
    <%= form_with(model: @user_label, url: labels_path, method: :post, local: true) do |label| %>
      <table>
        <tr><th><%= label.label :name %></th><td><%= label.text_field :name %></td></tr>
      </table>
      <%= label.hidden_field :user_id, value: current_user.id %>
      <%= label.submit 'ラベル登録する', class: 'btn btn-primary btn-sm' %>
      <%= link_to 'ラベル一覧画面', labels_path, class: 'btn btn-success btn-sm'%>
    <% end %>
  </div>
</div>