config/routes.rb
Rails.application.routes.draw do
  constraints ->  request { request.session[:user_id].present? } do
    root to: 'tasks#index'
  end
  root to: 'sessions#new'
  resources :tasks
  resources :users, only:[:new, :create, :show]
  resources :sessions, only:[:new, :create, :destroy]
  resources :labels

  namespace :admin do
    resources :users do
      collection do
        get :error
      end
    end
    resources :labels
  end
end

app/views/layouts/admin/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="refresh" content="5;URL=/tasks">
  </head>
  <body>
    <div class='container-fluid'>
      <div class='row'>
        <div class='col-md-12'>
          <% flash.each do |key, value| %>
            <% alert_color = key == 'notice' ? 'alert-success' : 'alert-danger' %>
            <%= content_tag(:div, value, class: "#{key} alert #{alert_color}") %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/admin/labels.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin - TaskManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='container-fluid'>
      <header class='admin_backcolor'>
        <div class='row'>
          <div class='col-md-8'>
            <h1>タスク管理システム</h1>
          </div>
          <% if logged_in? %>
            <% if Admin.find_by(user_id: current_user.id) %>
              <div class='col-md-1 top_menu'>
                <%= link_to 'Admin', admin_users_path %>
              </div>
            <% else %>
              <div class='col-md-1 top_menu'></div>
            <% end %>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Task', tasks_path %>
            </div>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Profile', user_path(current_user.id) %>
            </div>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Logout', session_path(current_user.id), method: :delete %>
            </div>
          <% else %>
            <div class='col-md-1 top_menu'></div>
            <div class='col-md-2 top_menu'>
              <%= link_to 'Sign up', new_user_path %>
            </div>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Login', new_session_path %>
            </div>
          <% end %>
        </div>
      </header>
      <div class='row'>
        <div class='col-md-12'>
          <% flash.each do |key, value| %>
            <% alert_color = key == 'notice' ? 'alert-success' : 'alert-danger' %>
            <%= content_tag(:div, value, class: "#{key} alert #{alert_color}") %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/admin/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin - TaskManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='container-fluid'>
      <header class='admin_backcolor'>
        <div class='row'>
          <div class='col-md-8'>
            <h1>タスク管理システム</h1>
          </div>
          <% if logged_in? %>
            <% if Admin.find_by(user_id: current_user.id) %>
              <div class='col-md-1 top_menu'>
                <%= link_to 'Admin', admin_users_path %>
              </div>
            <% else %>
              <div class='col-md-1 top_menu'></div>
            <% end %>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Task', tasks_path %>
            </div>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Profile', user_path(current_user.id) %>
            </div>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Logout', session_path(current_user.id), method: :delete %>
            </div>
          <% else %>
            <div class='col-md-1 top_menu'></div>
            <div class='col-md-2 top_menu'>
              <%= link_to 'Sign up', new_user_path %>
            </div>
            <div class='col-md-1 top_menu'>
              <%= link_to 'Login', new_session_path %>
            </div>
          <% end %>
        </div>
      </header>
      <div class='row'>
        <div class='col-md-12'>
          <% flash.each do |key, value| %>
            <% alert_color = key == 'notice' ? 'alert-success' : 'alert-danger' %>
            <%= content_tag(:div, value, class: "#{key} alert #{alert_color}") %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>