config/routes.rb
Rails.application.routes.draw do
  constraints ->  request { request.session[:user_id].present? } do
    root to: 'tasks#index'
  end
  root to: 'sessions#new'
  resources :tasks
  resources :users, only:[:new, :create, :show]
  resources :sessions, only:[:new, :create, :destroy]
  resources :labels

  namespace :admin do
    resources :users do
      collection do
        get :error
      end
    end
    resources :labels
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :admin, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :user_labels, dependent: :destroy
  accepts_nested_attributes_for :admin, allow_destroy: true

  has_secure_password
  before_validation { email&.downcase! }

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }

  scope :latest, -> { order(created_at: :asc).includes(:tasks) }
  scope :search_ransack, -> (_page){ ransack(_page) }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_admin_user, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.latest
  end

  def new
    @user = User.new
    @user.build_admin
  end

  def create
    params[:user][:admin_attributes] = nil if params[:user][:admin_attributes][:user_id] == '無'
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'アカウント作成しました'
    else
      @user.build_admin
      render 'new'
    end
  end

  def edit; end

  def update
    if params[:user][:admin_attributes][:user_id] == '無'
      unless @user.admin.destroy
        flash[:danger] = '管理者権限を持つユーザーを0人にすることは出来ません'
      end
      params[:user][:admin_attributes] = nil
    end

    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ID#{@user.id}番のユーザーを編集しました"
    else
      flash.now[:danger] = "ID#{@user.id}番のユーザーの編集に失敗しました"
      render 'edit'
    end
  end

  def show
    @tasks = Task.user_task_list(@user.id)
  end

  def destroy
    if @user.destroy
      flash[:notice] = "ID#{@user.id}番のユーザーを削除しました"
    else
      flash[:danger] = '管理者権限を持つユーザーを0人にすることは出来ません'
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      admin_attributes: %i[id user_id]
      )
  end

  def set_admin_user
    @user = User.find(params[:id])
    if @user.admin.nil?
      @user.build_admin
      @user.admin.user_id = nil
    end
  end

  def require_admin
    if logged_in?
      unless Admin.find_by(user_id: current_user.id)
        flash[:error] = 'このセクションにアクセス出来るのは、管理者権限のあるユーザーのみです'
        render :layout => 'admin/error', action: 'error'
      end
    else
      flash[:error] = 'ログインしていたアカウントが見つかりません'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'アカウント作成しました'
    else
      render 'new'
    end
  end

  def show
    if current_user.id == params[:id].to_i
      @user = User.find(params[:id])
    else
      flash[:error] = '他ユーザーのProfileは閲覧出来ません'
      redirect_to tasks_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_login
    if logged_in?
      flash[:error] = 'このセクションにアクセスするにはログアウトして下さい'
      redirect_to tasks_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class='row field'>
  <div class='col-md-12'>
    <h2>管理画面【ユーザー編集画面】</h2>
  </div>
</div>

<div class='row field'>
  <div class='col-md-12'>
    <% if @user.errors.any? %>
      <div id='error_explanation' class='alert alert alert-danger'>
        <h2>このユーザーを保存出来ません【<%= pluralize(@user.errors.count, 'error') %>】</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<div class= 'row field'>
  <div class='col-md-12'>
    <%= form_with(model: @user, url: admin_user_path(@user.id), method: :patch, local: true) do |user| %>
      <table>
        <tr><th><%= user.label :name %></th><td><%= user.text_field :name %></td></tr>
        <tr><th><%= user.label :email %></th><td><%= user.email_field :email %></td></tr>
        <tr><th><%= user.label :password %></th><td><%= user.password_field :password %></td></tr>
        <tr><th><%= user.label :password_confirmation %></th><td><%= user.password_field :password_confirmation %></td></tr>
        <%= user.fields_for :admin do |admin| %>
          <tr>
            <th>管理者権限</th>
            <td>
              <% if @user.admin.user_id.nil? %>
                <label><%= admin.radio_button :user_id, @user[:id] %>有</label>
                <label><%= admin.radio_button :user_id, '無', checked: true %>無</label>
              <% else %>
                <label><%= admin.radio_button :user_id, @user.admin[:user_id], checked: true %>有</label>
                <label><%= admin.radio_button :user_id, '無' %>無</label>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <%= user.submit 'アカウント更新する', class: 'btn btn-primary btn-sm' %>
      <%= link_to 'ユーザー一覧', admin_users_path, class: 'btn btn-success btn-sm' %>
      <%= link_to 'ユーザー詳細', admin_user_path(@user.id), class: 'btn btn-info btn-sm' %>
    <% end %>
  </div>
</div>

app/views/admin/users/error.html.erb
<div class='row error_page'>
  <div class='col-md-12'>
    <div class='center'>
      <b>管理者権限のないユーザーからアクセスがありました。</b><br>
      <b>5秒後にタスク一覧ページに戻ります</b>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class='row field'>
  <div class='col-md-12'>
    <h2>管理画面【ユーザー一覧画面】</h2>
  </div>
</div>

<div class='row field'>
  <div class='col-md-12 field'>
    <%= link_to 'ユーザーを新規登録する', new_admin_user_path, class: 'btn btn-success btn-sm'%>
    <%= link_to 'ラベル一覧画面', admin_labels_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>

<!-- TODO: ransackとkaminari -->
<div class='row field'>
  <div class='col-md-12'>
    <table border=1>
      <tr>
        <th>admin</th>
        <td>id</td>
        <td>name</td>
        <td>email</td>
        <td>task数</td>
      </tr>

      <% @users.each do |user| %>
        <tr>
          <th><% unless user.admin.nil? %>★<% end %></th>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.count %></td>
          <td><%= link_to '詳細', admin_user_path(user.id), class: 'btn btn-info btn-sm' %></td>
          <td><%= link_to '編集', edit_admin_user_path(user.id), class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to '削除', admin_user_path(user.id), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class='row field'>
  <div class='col-md-12'>
    <h2>管理画面【ユーザー新規登録画面】</h2>
  </div>
</div>

<div class='row field'>
  <div class='col-md-12'>
    <% if @user.errors.any? %>
      <div id='error_explanation' class='alert alert-danger'>
        <h2>このユーザーを保存出来ません【<%= pluralize(@user.errors.count, 'error') %>】</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<div class= 'row field'>
  <div class='col-md-12'>
    <%= form_with(model: @user, url: admin_users_path, method: :post, local: true) do |user| %>
      <table>
        <tr><th><%= user.label :name %></th><td><%= user.text_field :name %></td></tr>
        <tr><th><%= user.label :email %></th><td><%= user.email_field :email %></td></tr>
        <tr><th><%= user.label :password %></th><td><%= user.password_field :password %></td></tr>
        <tr><th><%= user.label :password_confirmation %></th><td><%= user.password_field :password_confirmation %></td></tr>
        <%= user.fields_for :admin do |admin| %>
          <tr>
            <th>管理者権限</th>
            <td>
              <label><%= admin.radio_button :user_id, '有' %>有</label>
              <label><%= admin.radio_button :user_id, '無', checked: true %>無</label>
            </td>
          </tr>
        <% end %>
      </table>
      <%= user.submit 'アカウント登録する', class: 'btn btn-primary btn-sm' %>
      <%= link_to 'ユーザー一覧画面',admin_users_path ,class: 'btn btn-success btn-sm'%>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='row field'>
  <div class='col-md-12'>
    <h2>管理画面【ユーザー詳細画面】</h2>
    <h3><%= @user.name %>のページ</h3>
    <table border=1>
      <tr><th>メールアドレス:</th><td><%= @user.email %></td></tr>
      <tr>
        <th>管理者権限：</th>
        <td>
          <% if @user.admin.user_id.nil? %>
            無
          <% else %>
            有
          <% end %>
        </td>
      </tr>
    </table>
    <br>
    <h2>登録したタスク一覧 / <%= @tasks.count %>件</h2>
    <table border=1>
      <tr>
        <th>Subject</th>
        <th>Content</th>
        <th>Created_at</th>
        <th>Expired_at</th>
        <th>State</th>
        <th>priority</th>
      </tr>

      <% @tasks.each do |task| %>
        <% if task.state == '未着手' %>
          <tr class='task_not_running'>
        <% elsif task.state == '着手中' %>
          <tr class='task_running'>
        <% else %>
          <tr class='task_done'>
        <% end %>
            <td><%= task.subject %></td>
            <td><%= task.content %></td>
            <td><%= task.created_at%></td>
            <td><%= task.expired_at %></td>
            <td><%= task.state %></td>
            <td><%= task.priority %></td>
          </tr>
        <% end %>
    </table>
    <br>
    <%= link_to 'ユーザー一覧', admin_users_path, class: 'btn btn-success btn-sm' %>
    <%= link_to 'ユーザー編集', edit_admin_user_path(@user.id), class: 'btn btn-warning btn-sm' %>
  </div>
</div>